spring:
  datasource:
    url: jdbc:mysql://rose.ciu3kns51x2y.ap-southeast-1.rds.amazonaws.com:3306/report?useUnicode=false&amp;autoReconnect=true&amp;characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: tempuser
    password: baie2018#

kettle:
  home: /home/ec2-user/kettle7/data-integration
  work: /home/ec2-user/kettle7/kettle/work