spring:
  profiles:
    active: test
  freemarker:
    cache: false
    suffix: .html
    expose-request-attributes: true
    request-context-attribute: request
    check-template-location: true
    charset: utf-8
server:
  port: 8899

logging:
  level:
    org.springframework.web: ERROR
    com.rose.scheduler: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


