spring:
  datasource:
    url: jdbc:mysql://rm-bp1is9caac5z435j0o.mysql.rds.aliyuncs.com:3306/task?useUnicode=false&amp;autoReconnect=true&amp;characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: fuwu
    password: baie_test_2017
  freemarker:
    cache: false
    suffix: .html
    expose-request-attributes: true
    request-context-attribute: request
    check-template-location: true
    charset: utf-8